
[env]
TERM = "alacritty"

[font]
size = 11

[font.normal]
family = "JetBrainsMonoNL NF"

[terminal.shell]
program = "/bin/fish"

[window]
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 0
y = 0

[general]
live_config_reload = false
ipc_socket = false
import = ["/home/davide/repos/alacritty-theme/themes/kanagawa_dragon.toml"]

[terminal]
